# Generated by Django 3.2.4 on 2021-06-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mobile_number', models.CharField(max_length=500)),
                ('alternate_number', models.CharField(max_length=500)),
                ('shop_name', models.CharField(max_length=500)),
                ('shop_address', models.CharField(max_length=500)),
                ('shop_services', models.CharField(max_length=500)),
                ('service_area', models.CharField(max_length=500)),
                ('service_time', models.CharField(max_length=500)),
                ('emergency_service', models.CharField(max_length=50)),
                ('register_by', models.CharField(max_length=500)),
                ('register_on', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(max_length=500)),
            ],
        ),
    ]
