# Generated by Django 3.2.4 on 2021-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mechanic_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance_Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mobile_number', models.CharField(max_length=500)),
                ('alternate_number', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('distric', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('problem_related_to', models.CharField(max_length=500)),
                ('problem_discription', models.CharField(max_length=500)),
                ('photo_of_problem', models.FileField(upload_to='media')),
                ('is_crain_required', models.CharField(max_length=50)),
                ('register_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
