# Generated by Django 3.2.4 on 2021-06-18 12:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
            ],
        ),
    ]
